/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpsellsRouteImport } from './routes/upsells'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PagamentoIdRouteImport } from './routes/pagamento.$id'
import { Route as ConfirmacaoIdRouteImport } from './routes/confirmacao.$id'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as ApiPublicPixWebhookRouteImport } from './routes/api/public/pix-webhook'

const UpsellsRoute = UpsellsRouteImport.update({
  id: '/upsells',
  path: '/upsells',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoIdRoute = PagamentoIdRouteImport.update({
  id: '/pagamento/$id',
  path: '/pagamento/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmacaoIdRoute = ConfirmacaoIdRouteImport.update({
  id: '/confirmacao/$id',
  path: '/confirmacao/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPixWebhookRoute = ApiPublicPixWebhookRouteImport.update({
  id: '/api/public/pix-webhook',
  path: '/api/public/pix-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/upsells': typeof UpsellsRoute
  '/admin/login': typeof AdminLoginRoute
  '/confirmacao/$id': typeof ConfirmacaoIdRoute
  '/pagamento/$id': typeof PagamentoIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/pix-webhook': typeof ApiPublicPixWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/upsells': typeof UpsellsRoute
  '/admin/login': typeof AdminLoginRoute
  '/confirmacao/$id': typeof ConfirmacaoIdRoute
  '/pagamento/$id': typeof PagamentoIdRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/pix-webhook': typeof ApiPublicPixWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/upsells': typeof UpsellsRoute
  '/admin/login': typeof AdminLoginRoute
  '/confirmacao/$id': typeof ConfirmacaoIdRoute
  '/pagamento/$id': typeof PagamentoIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/pix-webhook': typeof ApiPublicPixWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/upsells'
    | '/admin/login'
    | '/confirmacao/$id'
    | '/pagamento/$id'
    | '/admin/'
    | '/api/public/pix-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/upsells'
    | '/admin/login'
    | '/confirmacao/$id'
    | '/pagamento/$id'
    | '/admin'
    | '/api/public/pix-webhook'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/upsells'
    | '/admin/login'
    | '/confirmacao/$id'
    | '/pagamento/$id'
    | '/admin/'
    | '/api/public/pix-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  UpsellsRoute: typeof UpsellsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ConfirmacaoIdRoute: typeof ConfirmacaoIdRoute
  PagamentoIdRoute: typeof PagamentoIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiPublicPixWebhookRoute: typeof ApiPublicPixWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upsells': {
      id: '/upsells'
      path: '/upsells'
      fullPath: '/upsells'
      preLoaderRoute: typeof UpsellsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento/$id': {
      id: '/pagamento/$id'
      path: '/pagamento/$id'
      fullPath: '/pagamento/$id'
      preLoaderRoute: typeof PagamentoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmacao/$id': {
      id: '/confirmacao/$id'
      path: '/confirmacao/$id'
      fullPath: '/confirmacao/$id'
      preLoaderRoute: typeof ConfirmacaoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pix-webhook': {
      id: '/api/public/pix-webhook'
      path: '/api/public/pix-webhook'
      fullPath: '/api/public/pix-webhook'
      preLoaderRoute: typeof ApiPublicPixWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  UpsellsRoute: UpsellsRoute,
  AdminLoginRoute: AdminLoginRoute,
  ConfirmacaoIdRoute: ConfirmacaoIdRoute,
  PagamentoIdRoute: PagamentoIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiPublicPixWebhookRoute: ApiPublicPixWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
